CURSO_DATA_ENGINEERING_2025.BRONZE.BRONZE_STAGEcreate or replace database dev_curso_db_alumno_03;

create or replace schema bronze;


-- Create Events --
CREATE TABLE EVENTS(
	EVENT_ID VARCHAR(256),
	PAGE_URL VARCHAR(256),
	EVENT_TYPE VARCHAR(256),
	USER_ID VARCHAR(256),
	PRODUCT_ID VARCHAR(256),
	SESSION_ID VARCHAR(256),
	CREATED_AT VARCHAR(256),
	ORDER_ID VARCHAR(256)
);

-- Create ORDER_ITEMS --
CREATE TABLE ORDER_ITEMS(
	ORDER_ID VARCHAR(256),
	PRODUCT_ID VARCHAR(256),
	QUANTITY VARCHAR(256)
);

-- Create ORDERS --
CREATE TABLE ORDERS(
	ORDER_ID VARCHAR(256),
	SHIPPING_SERVICE VARCHAR(256),
	SHIPPING_COST VARCHAR(256),
	ADDRESS_ID VARCHAR(256),
	CREATED_AT VARCHAR(256),
	PROMO_ID VARCHAR(256),
	ESTIMATED_DELIVERY_AT VARCHAR(256),
	ORDER_COST VARCHAR(256),
	USER_ID VARCHAR(256),
	ORDER_TOTAL VARCHAR(256),
	DELIVERED_AT VARCHAR(256),
	TRACKING_ID VARCHAR(256),
	STATUS VARCHAR(256)
);

-- Create PRODUCTS --
CREATE TABLE PRODUCTS(
	PRODUCT_ID VARCHAR(256),
	PRICE VARCHAR(256),
	NAME VARCHAR(256),
	INVENTORY VARCHAR(256)
);

-- Create PROMOS --
CREATE TABLE PROMOS(
	PROMO_ID VARCHAR(256),
	DISCOUNT VARCHAR(256),
	STATUS VARCHAR(256)
);

-- Create Users --
CREATE TABLE USERS(
	USER_ID VARCHAR(256),
	UPDATED_AT VARCHAR(256),
	ADDRESS_ID VARCHAR(256),
	LAST_NAME VARCHAR(256),
	CREATED_AT VARCHAR(256),
	PHONE_NUMBER VARCHAR(256),
	TOTAL_ORDERS VARCHAR(256),
	FIRST_NAME VARCHAR(256),
	EMAIL VARCHAR(256)
);

-- Create Addresses --
CREATE TABLE ADDRESSES(
    ADDRESS_ID VARCHAR(256),
    ZIPCODE VARCHAR(256),
    COUNTRY VARCHAR(256),
    ADDRESS VARCHAR(256),
    STATE VARCHAR(256)
    );

CREATE FILE FORMAT diferetent_format
    TYPE = 'CSV'
    FIELD_DELIMITER = ';'
    SKIP_HEADER = 1
  

    --Copiar datos de internal storage --
    COPY INTO ORDER_ITEMS
    FROM @CURSO_DATA_ENGINEERING_2025.BRONZE.BRONZE_STAGE/order_items.csv
    FILE_FORMAT = (FORMAT_NAME = 'diferetent_format');

    COPY INTO EVENTS   
    FROM @CURSO_DATA_ENGINEERING_2025.BRONZE.BRONZE_STAGE/events.csv
    FILE_FORMAT = (FORMAT_NAME = 'diferetent_format');

    COPY INTO ADDRESSES   
    FROM @CURSO_DATA_ENGINEERING_2025.BRONZE.BRONZE_STAGE/addresses.csv
    FILE_FORMAT = (FORMAT_NAME = 'diferetent_format');

    COPY INTO USERS   
    FROM @CURSO_DATA_ENGINEERING_2025.BRONZE.BRONZE_STAGE/users.csv
    FILE_FORMAT = (FORMAT_NAME = 'diferetent_format');

    COPY INTO ORDERS   
    FROM @CURSO_DATA_ENGINEERING_2025.BRONZE.BRONZE_STAGE/orders.csv
    FILE_FORMAT = (FORMAT_NAME = 'diferetent_format');

    --Crear el stage--
    CREATE STAGE my_stage
    FILE_FORMAT = (FORMAT_NAME = 'diferetent_format');

--COPY INTO DE ALMACENAMIENTO INTERNAL STAGE-- 
COPY INTO PRODUCTS
FROM
@DEV_CURSO_DB_ALUMNO_03.BRONZE.MY_STAGE/products.csv.gz
FILE_FORMAT= ( FORMAT_NAME = 'second_format');

COPY INTO PROMOS
FROM
@DEV_CURSO_DB_ALUMNO_03.BRONZE.MY_STAGE/promos.csv.gz
FILE_FORMAT= ( FORMAT_NAME = 'second_format');

CREATE OR REPLACE FILE FORMAT second_format
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY= '"'
NULL_IF = ('', 'NULL');