USE ROLE CURSO_DATA_ENGINEERING;
USE WAREHOUSE WH_CURSO_DATA_ENGINEERING;

-- 👇 Sustituye MY_DB por el nombre de tu base de datos
USE DATABASE DEV_CURSO_DB_ALUMNO_03;

-- 👇 Crea una base de datos clonada con el nombre que elijas
CREATE OR REPLACE DATABASE DEV_CURSO_DB_ALUMNO_03_CLONED
CLONE CURSO_DATA_ENGINEERING_TO_BE_CLONED;


CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03_CLONED.GOLD.ORDERS_STATUS_DATE AS (
    SELECT 
        TO_DATE(CREATED_AT) AS FECHA_CREACION_PEDIDO,
        STATUS,
        COUNT(DISTINCT ORDER_ID) AS NUM_PEDIDOS
    FROM 
        MY_DB.SILVER.ORDERS 
    GROUP BY    
        TO_DATE(CREATED_AT),
        STATUS
    ORDER BY 1 DESC
);


--PROCEDURE--

CREATE OR REPLACE PROCEDURE DEV_CURSO_DB_ALUMNO_03_CLONED.GOLD.update_gold_orders_status()
RETURNS VARCHAR
LANGUAGE SQL
AS
BEGIN

    CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03_CLONED.ORDERS_STATUS_DATE AS (
        SELECT 
            TO_DATE(CREATED_AT) AS FECHA_CREACION_PEDIDO,
            STATUS,
            COUNT(DISTINCT ORDER_ID) AS NUM_PEDIDOS
        FROM 
            MY_DB.SILVER.ORDERS
        GROUP BY    
            TO_DATE(CREATED_AT),
            STATUS
        ORDER BY 1 DESC
    );

    return 'Tabla ORDERS_STATUS_DATE actualizada con éxito';
END;

--stream--

CREATE OR REPLACE STREAM ORDER_STREAM
ON TABLE CURSO_DATA_ENGINEERING_TO_BE_CLONED.BRONZE.ORDERS_HIST
APPEND_ONLY = TRUE

SHOW STREAMS

--VER LAS FILAS QUE SE INSERTAN CADA 30 SEGUNDOS
SELECT * FROM ORDER_STREAM

--TASK--

CREATE OR REPLACE TASK ROOT_TASK
WAREHOUSE = WH_CURSO_DATA_ENGINEERING
SCHEDULE = '30 SECONDS'
WHEN SYSTEM$STREAM_HAS_DATA('ORDERS_STREAM') AS 
    MERGE INTO DEV_CURSO_DB_ALUMNO_03_CLONED.SILVER.ORDERS t
    USING 
    (
        SELECT 
            ORDER_ID::varchar(100)AS ORDER_ID,
            SHIPPING_SERVICE::varchar(20) AS SHIPPING_SERVICE,
            replace(SHIPPING_COST,',','.')::decimal AS SHIPPING_COST,
            ADDRESS_ID::varchar(50) AS ADDRESS_ID,
            CREATED_AT::timestamp_ntz AS CREATED_AT,
            IFNULL(promo_id,'N/A') AS PROMO_NAME,
            ESTIMATED_DELIVERY_AT::timestamp_ntz AS CREATED_AT,
            (replace(ORDER_COST,',','.'))::decimal AS ORDER_COST,
            USER_ID::varchar(50) AS USER_ID,
            (replace(ORDER_TOTAL,',','.'))::decimal AS ORDER_TOTAL,
            DELIVERED_AT::timestamp_ntz AS DELIVERED_AT,
            TRACKING_ID::varchar(50) AS TRACKING_ID,
            STATUS::varchar(20) AS STATUS,
            TIMESTAMPDIFF(HOUR,created_at,delivered_at)
        FROM
           DEV_CURSO_DB_ALUMNO_03.BRONZE.ORDERS_STREAM 
    ) s ON t.ORDER_ID = s.ORDER_ID
            WHEN MATCHED THEN 
            UPDATE ALL BY NAME
            WHEN NOT MATCHED THEN
            INSERT ALL BY NAME;


-- TASK HIJA--
CREATE OR REPLACE TASK HIJA
WAREHOUSE = WH_CURSO_DATA_ENGINEERING
AFTER ROOT_TASK AS 
CALL DEV_CURSO_DB_ALUMNO_03_CLONED.GOLD.update_gold_orders_status();

--ACTIVAR LAS TAREAS--
ALTER TASK IF EXISTS DEV_CURSO_DB_ALUMNO_03_CLONED.GOLD.TASK_HIJA RESUME;
ALTER TASK IF EXISTS DEV_CURSO_DB_ALUMNO_03_CLONED.BRONZE.ROOT_TASK RESUME;

--CHECK TASK HISTORY
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY())
WHERE NAME = 'ROOT_TASK';


--COMPROBACION--
SELECT * FROM GOLD.ORDERS_STATUS_DATE;

--SUSPENSION DE LAS TASKS--
ALTER TASK DEV_CURSO_DB_ALUMNO_03_CLONED.PUBLIC.ROOT_TASK SUSPEND;
ALTER TASK DEV_CURSO_DB_ALUMNO_03_CLONED.PUBLIC.HIJA SUSPEND;

DROP TASK DEV_CURSO_DB_ALUMNO_03_CLONED.PUBLIC.ROOT_TASK;
DROP TASK DEV_CURSO_DB_ALUMNO_03_CLONED.PUBLIC.HIJA;

--PRACTICA EXTRA--

CREATE OR REPLACE SCHEMA SEMIESTRUCTURADOS

USE DATABASE DEV_CURSO_DB_ALUMNO_03_CLONED.BRONZE;
USE SCHEMA SEMIESTRUCTURADOS;
