--CLONACION DE UNA BASE DE DATOS A OTRA.
CREATE OR REPLACE SCHEMA DEV_CURSO_DB_ALUMNO_03.BRONZE
CLONE CURSO_DATA_ENGINEERING_2025.BRONZE;

--CREAR SCHEMA SILVER--
CREATE OR REPLACE SCHEMA DEV_CURSO_DB_ALUMNO_03.SILVER


-- SILVER

--  ORDERS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.ORDERS (
    ORDER_ID VARCHAR(50),
    SHIPPING_SERVICE VARCHAR(20),
    SHIPPING_COST FLOAT,
    ADDRESS_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    Promo_Name VARCHAR(50),
    ESTIMATED_DELIVERY_AT TIMESTAMP_NTZ,
    ORDER_COST FLOAT,
    USER_ID VARCHAR(50),
    ORDER_TOTAL FLOAT,
    DELIVERED_AT TIMESTAMP_NTZ,
    TRACKING_ID VARCHAR(50),
    STATUS VARCHAR(20),
    Delivery_time_hours INT
);

-- EVENTS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.EVENTS (
    EVENT_ID VARCHAR(50),
    PAGE_URL VARCHAR(200),
    EVENT_TYPE VARCHAR(50),
    USER_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    SESSION_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    ORDER_ID VARCHAR(50),
    Hit_number INT
);

-- PRODUCTS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.PRODUCTS (
    PRODUCT_ID VARCHAR(50),
    PRICE FLOAT,
    NAME VARCHAR(100),
    INVENTORY NUMBER(38,0)
);

-- ADDRESSES
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.ADDRESSES (
    ADDRESS_ID VARCHAR(50),
    ZIPCODE NUMBER(38,0),
    COUNTRY VARCHAR(50),
    ADDRESS VARCHAR(150),
    STATE VARCHAR(50)
);

-- USERS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.USERS (
    USER_ID VARCHAR(50),
    UPDATED_AT TIMESTAMP_NTZ,
    ADDRESS_ID VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ,
    PHONE_NUMBER VARCHAR(20),
    FIRST_NAME VARCHAR(50),
    EMAIL VARCHAR(100)
);

-- ORDER_ITEMS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.ORDER_ITEMS (
    ORDER_ID VARCHAR(50),
    PRODUCT_ID VARCHAR(50),
    QUANTITY NUMBER(38,0)
);

-- PROMOS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.PROMOS (
    PROMO_ID VARCHAR(50),
    DISCOUNT FLOAT,
    STATUS VARCHAR(50)
);

--COPY INTO PARA SILVER--

--ORDERS--
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.ORDERS 
SELECT 
    ORDER_ID::VARCHAR(50),
    SHIPPING_SERVICE::VARCHAR(20),
    CAST(TRY_TO_NUMBER(REPLACE(SHIPPING_COST, ',', '.')) AS NUMBER(16,2)),
    ADDRESS_ID::VARCHAR(50),
    CREATED_AT::TIMESTAMP_NTZ,
    Promo_id::VARCHAR(50),
    ESTIMATED_DELIVERY_AT::TIMESTAMP_NTZ,
    CAST(TRY_TO_NUMBER(REPLACE(ORDER_COST,',', '.'))AS NUMERIC(16,2)),
    USER_ID::VARCHAR(50),
    CAST(TRY_TO_NUMBER(REPLACE(ORDER_TOTAL, ',', '.'))AS NUMERIC(16,2)),
    DELIVERED_AT::TIMESTAMP_NTZ,
    TRACKING_ID::VARCHAR(50),
    STATUS::VARCHAR(20),
    DATEDIFF('HOUR', CREATED_AT, DELIVERED_AT) AS Delivery_time_hours
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.orders;


-- EVENTS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.EVENTS 
SELECT 
    EVENT_ID::VARCHAR(50),
    PAGE_URL::VARCHAR(200),
    EVENT_TYPE::VARCHAR(50),
    USER_ID::VARCHAR(50),
    PRODUCT_ID::VARCHAR(50),
    SESSION_ID ::VARCHAR(50),
    CREATED_AT::TIMESTAMP_NTZ,
    ORDER_ID::VARCHAR(50),
    ROW_NUMBER()OVER(PARTITION BY SESSION_ID ORDER BY CREATED_AT) as Hit_number
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.events;


-- PRODUCTS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.PRODUCTS 
SELECT 
    PRODUCT_ID::VARCHAR(50),
    REPLACE(PRICE, ',','.')::NUMERIC(16,4),
    NAME::VARCHAR(100),
    INVENTORY::NUMBER(38,0)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.products;


-- ADDRESSES
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.ADDRESSES 
SELECT 
    ADDRESS_ID::VARCHAR(50),
    ZIPCODE::NUMBER(38,0),
    COUNTRY::VARCHAR(50),
    ADDRESS::VARCHAR(150),
    STATE::VARCHAR(50)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.addresses;


-- USERS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.USERS 
SELECT 
    USER_ID::VARCHAR(50),
    UPDATED_AT::TIMESTAMP_NTZ,
    ADDRESS_ID::VARCHAR(50),
    LAST_NAME::VARCHAR(50),
    CREATED_AT::TIMESTAMP_NTZ,
    PHONE_NUMBER::VARCHAR(20),
    FIRST_NAME::VARCHAR(50),
    EMAIL::VARCHAR(100)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.users;

-- ORDER_ITEMS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.ORDER_ITEMS 
SELECT 
    ORDER_ID::VARCHAR(50),
    PRODUCT_ID::VARCHAR(50),
    QUANTITY::NUMBER(38,0)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.order_items;


-- PROMOS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.PROMOS 
SELECT 
    PROMO_ID::varchar(50),
    DISCOUNT::float,
    STATUS::varchar(50)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.promos;



--PROCEDURES CAPA SILVER--

CREATE OR REPLACE PROCEDURE INSERT_PROCEDURE()
    RETURNS VARCHAR
    LANGUAGE SQL
    EXECUTE AS CALLER
AS
BEGIN

    -- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.PROMOS;

    -- Insert de la tabla
    INSERT INTO MY_DB.MY_SILVER_SCHEMA.PROMOS 
    SELECT 
        PROMO_ID::varchar(50),
        DISCOUNT::float,
        STATUS::varchar(50)
    FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.promos;

-- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.ORDERS;

--ORDERS--
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.ORDERS
SELECT 
    ORDER_ID::VARCHAR(50),
    SHIPPING_SERVICE::VARCHAR(20),
    CAST(TRY_TO_NUMBER(REPLACE(SHIPPING_COST, ',', '.')) AS NUMBER(16,2)),
    ADDRESS_ID::VARCHAR(50),
    CREATED_AT::TIMESTAMP_NTZ,
    Promo_id::VARCHAR(50),
    ESTIMATED_DELIVERY_AT::TIMESTAMP_NTZ,
    CAST(TRY_TO_NUMBER(REPLACE(ORDER_COST,',', '.'))AS NUMERIC(16,2)),
    USER_ID::VARCHAR(50),
    CAST(TRY_TO_NUMBER(REPLACE(ORDER_TOTAL, ',', '.'))AS NUMERIC(16,2)),
    DELIVERED_AT::TIMESTAMP_NTZ,
    TRACKING_ID::VARCHAR(50),
    STATUS::VARCHAR(20),
    DATEDIFF('HOUR', CREATED_AT, DELIVERED_AT) AS Delivery_time_hours
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.orders;

 -- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.EVENTS;

-- EVENTS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.EVENTS 
SELECT 
    EVENT_ID::VARCHAR(50),
    PAGE_URL::VARCHAR(200),
    EVENT_TYPE::VARCHAR(50),
    USER_ID::VARCHAR(50),
    PRODUCT_ID::VARCHAR(50),
    SESSION_ID ::VARCHAR(50),
    CREATED_AT::TIMESTAMP_NTZ,
    ORDER_ID::VARCHAR(50),
    ROW_NUMBER()OVER(PARTITION BY SESSION_ID ORDER BY CREATED_AT) as Hit_number
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.events;

 -- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.PRODUCTS;

-- PRODUCTS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.PRODUCTS 
SELECT 
    PRODUCT_ID::VARCHAR(50),
    REPLACE(PRICE, ',','.')::NUMERIC(16,4),
    NAME::VARCHAR(100),
    INVENTORY::NUMBER(38,0)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.products;

 -- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.ADDRESSES;

-- ADDRESSES
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.ADDRESSES 
SELECT 
    ADDRESS_ID::VARCHAR(50),
    ZIPCODE::NUMBER(38,0),
    COUNTRY::VARCHAR(50),
    ADDRESS::VARCHAR(150),
    STATE::VARCHAR(50)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.addresses;

 -- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.USERS;

-- USERS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.USERS
SELECT 
    USER_ID::VARCHAR(50),
    UPDATED_AT::TIMESTAMP_NTZ,
    ADDRESS_ID::VARCHAR(50),
    LAST_NAME::VARCHAR(50),
    CREATED_AT::TIMESTAMP_NTZ,
    PHONE_NUMBER::VARCHAR(20),
    FIRST_NAME::VARCHAR(50),
    EMAIL::VARCHAR(100)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.users;

-- Truncado de la tabla
    TRUNCATE TABLE DEV_CURSO_DB_ALUMNO_03.SILVER.ORDER_ITEMS;

-- ORDER_ITEMS
INSERT INTO DEV_CURSO_DB_ALUMNO_03.SILVER.ORDER_ITEMS 
SELECT 
    ORDER_ID::VARCHAR(50),
    PRODUCT_ID::VARCHAR(50),
    QUANTITY::NUMBER(38,0)
FROM DEV_CURSO_DB_ALUMNO_03.BRONZE.order_items;

    RETURN 'Insertado con éxito máquina';
END;




--CAPA GOLD--

--CREAR SCHEMA GOLD--
CREATE OR REPLACE SCHEMA DEV_CURSO_DB_ALUMNO_03.GOLD

-- SESSION DETAILS
CREATE OR REPLACE TABLE DEV_CURSO_DB_ALUMNO_03.GOLD.session_details (
    session_id VARCHAR(50),
    Finish_with_Order BOOLEAN,
    Num_Eventos INT,
    Session_duration_minutes INT
);

INSERT INTO DEV_CURSO_DB_ALUMNO_03.GOLD.SESSION_DETAILS
SELECT
SESSION_ID,

FROM
DEV_CURSO_DB_ALUMNO_03.SILVER.EVENTS